apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  PORT: "5000"
  MONGO_URI: "mongodb://mongodb:27017/ecomdb"
  UPSTASH_REDIS_URL: "redis://redis:6379"
  CLIENT_URL: "http://frontend:5173"
  NODE_ENV: "development"
